import { sanityClient } from 'sanity:client';
import groq from 'groq';
import type { PortableTextBlock } from '@portabletext/types';

export { sanityClient };

export type PtBlocks = PortableTextBlock[];

export interface ImageAsset {
  url: string;
  mimeType: string;
  width?: number;
  height?: number;
  /** Tiny blurred preview as a data URL, generated by Sanity for raster images. */
  lqip?: string;
}

export interface SanityImage {
  _key?: string;
  asset: ImageAsset;
  alt?: string;
  caption?: string;
}

export interface Settings {
  title?: string;
  /** ISO 639-1 code */
  language?: string;
  seoTitle?: string;
  metaDescription?: string;
  siteUrl?: string;
  openGraphTitle?: string;
  openGraphDescription?: string;
  socialImageAlt?: string;
  favicon?: ImageAsset;
  socialImage?: ImageAsset;
  /** Shown above Imprint / Privacy in the site nav */
  navFooterText?: string;
}

export interface ProjectListItem {
  title: string;
  slug: string;
  coverImage?: SanityImage;
}

export interface ProjectMetadataItem {
  _key: string;
  title: string;
  content: string;
}

export interface TextSection {
  _type: 'textSection';
  _key: string;
  text?: PtBlocks;
}

export interface ImageSection extends SanityImage {
  _type: 'figure';
  _key: string;
}

export interface SlideshowSection {
  _type: 'slideshow';
  _key: string;
  images?: SanityImage[];
}

export interface VideoSection {
  _type: 'video';
  _key: string;
  asset?: { url: string; mimeType: string };
  poster?: ImageAsset;
  /** Muted, looping, without controls while on screen; `false` for a player with sound and controls. */
  loop?: boolean;
  /** Accessible description. */
  title?: string;
  caption?: string;
}

export type ColumnItem = TextSection | ImageSection;

export interface TwoColumnsSection {
  _type: 'twoColumns';
  _key: string;
  left?: ColumnItem[];
  right?: ColumnItem[];
}

export type ProjectSection = TextSection | ImageSection | SlideshowSection | TwoColumnsSection | VideoSection;

export interface Project extends ProjectListItem {
  metadata?: ProjectMetadataItem[];
  excerpt?: string;
  content?: ProjectSection[];
  seoTitle?: string;
  seoDescription?: string;
}

export interface About {
  text?: PtBlocks;
  seoTitle?: string;
  seoDescription?: string;
}

export interface Contact {
  text?: PtBlocks;
  seoTitle?: string;
  seoDescription?: string;
}

export interface LegalPage {
  title?: string;
  body?: PtBlocks;
}

export interface ImageUrlOptions {
  width?: number;
  height?: number;
  quality?: number;
  fit?: 'clip' | 'crop' | 'fill' | 'fillmax' | 'max' | 'min' | 'scale';
}

export function imageUrl(asset: ImageAsset, width: number, height: number): string;
export function imageUrl(asset: ImageAsset, options?: ImageUrlOptions): string;
export function imageUrl(asset: ImageAsset, widthOrOptions?: number | ImageUrlOptions, height?: number): string {
  if (asset.mimeType === 'image/svg+xml') return asset.url;

  const options =
    typeof widthOrOptions === 'number'
      ? { width: widthOrOptions, height, fit: 'crop' as const }
      : (widthOrOptions ?? {});
  const url = new URL(asset.url);

  if (options.width) url.searchParams.set('w', String(options.width));
  if (options.height) url.searchParams.set('h', String(options.height));
  if (options.fit) url.searchParams.set('fit', options.fit);
  if (options.quality) url.searchParams.set('q', String(options.quality));

  url.searchParams.set('auto', 'format');

  return url.toString();
}

export function imageSrcSet(
  asset: ImageAsset,
  widths: number[],
  options: Omit<ImageUrlOptions, 'width' | 'height'> & { width?: number; height?: number } = {},
): string | undefined {
  if (asset.mimeType === 'image/svg+xml') return undefined;

  const aspectRatio = options.width && options.height ? options.height / options.width : undefined;

  return widths
    .map(width => {
      const height = aspectRatio ? Math.round(width * aspectRatio) : undefined;
      return `${imageUrl(asset, { ...options, width, height })} ${width}w`;
    })
    .join(', ');
}

const assetProjection = groq`{
  url,
  mimeType,
  "width": metadata.dimensions.width,
  "height": metadata.dimensions.height,
  "lqip": metadata.lqip
}`;

const imageProjection = groq`{
  _key,
  alt,
  caption,
  "asset": asset->${assetProjection}
}`;

const columnProjection = groq`{
  _type,
  _key,
  _type == "textSection" => { text },
  _type == "figure" => ${imageProjection}
}`;

export async function getSettings(): Promise<Settings | null> {
  return await sanityClient.fetch(
    groq`*[_id == "settings"][0]{
      title,
      language,
      seoTitle,
      metaDescription,
      siteUrl,
      openGraphTitle,
      openGraphDescription,
      socialImageAlt,
      navFooterText,
      "favicon": favicon.asset->{ url, mimeType },
      "socialImage": socialImage.asset->{ url, mimeType }
    }`,
  );
}

export async function getProjectList(): Promise<ProjectListItem[]> {
  return await sanityClient.fetch(
    groq`*[_type == "project" && defined(slug.current)] | order(orderRank asc, title asc){
      title,
      "slug": slug.current,
      "coverImage": coverImage${imageProjection}
    }`,
  );
}

export async function getProjects(): Promise<Project[]> {
  return await sanityClient.fetch(
    groq`*[_type == "project" && defined(slug.current)] | order(orderRank asc, title asc){
      title,
      "slug": slug.current,
      metadata[]{ _key, title, content },
      excerpt,
      "coverImage": coverImage${imageProjection},
      "content": content[]{
        _type,
        _key,
        _type == "textSection" => { text },
        _type == "figure" => ${imageProjection},
        _type == "slideshow" => { "images": images[defined(asset)]${imageProjection} },
        _type == "twoColumns" => { "left": left[]${columnProjection}, "right": right[]${columnProjection} },
        _type == "video" => {
          "asset": file.asset->{ url, mimeType },
          "poster": poster.asset->${assetProjection},
          loop,
          title,
          caption
        }
      },
      seoTitle,
      seoDescription
    }`,
  );
}

export async function getAbout(): Promise<About | null> {
  return await sanityClient.fetch(
    groq`*[_id == "about"][0]{
      text,
      seoTitle,
      seoDescription
    }`,
  );
}

export async function getContact(): Promise<Contact | null> {
  return await sanityClient.fetch(
    groq`*[_id == "contact"][0]{
      text,
      seoTitle,
      seoDescription
    }`,
  );
}

export async function getLegalPage(id: 'imprint' | 'privacy'): Promise<LegalPage | null> {
  return await sanityClient.fetch(groq`*[_id == $id][0]{ title, body }`, { id });
}
