/** All ISO 639-1 languages (code + English name), sorted by name. */
export const languages = [
  {title: 'Abkhazian', value: 'ab'},
  {title: 'Afar', value: 'aa'},
  {title: 'Afrikaans', value: 'af'},
  {title: 'Akan', value: 'ak'},
  {title: 'Albanian', value: 'sq'},
  {title: 'Amharic', value: 'am'},
  {title: 'Arabic', value: 'ar'},
  {title: 'Aragonese', value: 'an'},
  {title: 'Armenian', value: 'hy'},
  {title: 'Assamese', value: 'as'},
  {title: 'Avaric', value: 'av'},
  {title: 'Avestan', value: 'ae'},
  {title: 'Aymara', value: 'ay'},
  {title: 'Azerbaijani', value: 'az'},
  {title: 'Bambara', value: 'bm'},
  {title: 'Bashkir', value: 'ba'},
  {title: 'Basque', value: 'eu'},
  {title: 'Belarusian', value: 'be'},
  {title: 'Bengali', value: 'bn'},
  {title: 'Bislama', value: 'bi'},
  {title: 'Bosnian', value: 'bs'},
  {title: 'Breton', value: 'br'},
  {title: 'Bulgarian', value: 'bg'},
  {title: 'Burmese', value: 'my'},
  {title: 'Catalan; Valencian', value: 'ca'},
  {title: 'Central Khmer', value: 'km'},
  {title: 'Chamorro', value: 'ch'},
  {title: 'Chechen', value: 'ce'},
  {title: 'Chichewa; Chewa; Nyanja', value: 'ny'},
  {title: 'Chinese', value: 'zh'},
  {
    title: 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
    value: 'cu',
  },
  {title: 'Chuvash', value: 'cv'},
  {title: 'Cornish', value: 'kw'},
  {title: 'Corsican', value: 'co'},
  {title: 'Cree', value: 'cr'},
  {title: 'Croatian', value: 'hr'},
  {title: 'Czech', value: 'cs'},
  {title: 'Danish', value: 'da'},
  {title: 'Divehi; Dhivehi; Maldivian', value: 'dv'},
  {title: 'Dutch; Flemish', value: 'nl'},
  {title: 'Dzongkha', value: 'dz'},
  {title: 'English', value: 'en'},
  {title: 'Esperanto', value: 'eo'},
  {title: 'Estonian', value: 'et'},
  {title: 'Ewe', value: 'ee'},
  {title: 'Faroese', value: 'fo'},
  {title: 'Fijian', value: 'fj'},
  {title: 'Finnish', value: 'fi'},
  {title: 'French', value: 'fr'},
  {title: 'Fulah', value: 'ff'},
  {title: 'Gaelic; Scottish Gaelic', value: 'gd'},
  {title: 'Galician', value: 'gl'},
  {title: 'Ganda', value: 'lg'},
  {title: 'Georgian', value: 'ka'},
  {title: 'German', value: 'de'},
  {title: 'Guarani', value: 'gn'},
  {title: 'Gujarati', value: 'gu'},
  {title: 'Haitian; Haitian Creole', value: 'ht'},
  {title: 'Hausa', value: 'ha'},
  {title: 'Hebrew', value: 'he'},
  {title: 'Herero', value: 'hz'},
  {title: 'Hindi', value: 'hi'},
  {title: 'Hiri Motu', value: 'ho'},
  {title: 'Hungarian', value: 'hu'},
  {title: 'Icelandic', value: 'is'},
  {title: 'Ido', value: 'io'},
  {title: 'Igbo', value: 'ig'},
  {title: 'Indonesian', value: 'id'},
  {title: 'Interlingua (International Auxiliary Language Association)', value: 'ia'},
  {title: 'Interlingue; Occidental', value: 'ie'},
  {title: 'Inuktitut', value: 'iu'},
  {title: 'Inupiaq', value: 'ik'},
  {title: 'Irish', value: 'ga'},
  {title: 'Italian', value: 'it'},
  {title: 'Japanese', value: 'ja'},
  {title: 'Javanese', value: 'jv'},
  {title: 'Kalaallisut; Greenlandic', value: 'kl'},
  {title: 'Kannada', value: 'kn'},
  {title: 'Kanuri', value: 'kr'},
  {title: 'Kashmiri', value: 'ks'},
  {title: 'Kazakh', value: 'kk'},
  {title: 'Kikuyu; Gikuyu', value: 'ki'},
  {title: 'Kinyarwanda', value: 'rw'},
  {title: 'Kirghiz; Kyrgyz', value: 'ky'},
  {title: 'Komi', value: 'kv'},
  {title: 'Kongo', value: 'kg'},
  {title: 'Korean', value: 'ko'},
  {title: 'Kuanyama; Kwanyama', value: 'kj'},
  {title: 'Kurdish', value: 'ku'},
  {title: 'Lao', value: 'lo'},
  {title: 'Latin', value: 'la'},
  {title: 'Latvian', value: 'lv'},
  {title: 'Limburgan; Limburger; Limburgish', value: 'li'},
  {title: 'Lingala', value: 'ln'},
  {title: 'Lithuanian', value: 'lt'},
  {title: 'Luba-Katanga', value: 'lu'},
  {title: 'Luxembourgish; Letzeburgesch', value: 'lb'},
  {title: 'Macedonian', value: 'mk'},
  {title: 'Malagasy', value: 'mg'},
  {title: 'Malay', value: 'ms'},
  {title: 'Malayalam', value: 'ml'},
  {title: 'Maltese', value: 'mt'},
  {title: 'Manx', value: 'gv'},
  {title: 'Maori', value: 'mi'},
  {title: 'Marathi', value: 'mr'},
  {title: 'Marshallese', value: 'mh'},
  {title: 'Modern Greek (1453-)', value: 'el'},
  {title: 'Mongolian', value: 'mn'},
  {title: 'Nauru', value: 'na'},
  {title: 'Navajo; Navaho', value: 'nv'},
  {title: 'Ndonga', value: 'ng'},
  {title: 'Nepali', value: 'ne'},
  {title: 'North Ndebele', value: 'nd'},
  {title: 'Northern Sami', value: 'se'},
  {title: 'Norwegian', value: 'no'},
  {title: 'Norwegian Bokmål', value: 'nb'},
  {title: 'Norwegian Nynorsk', value: 'nn'},
  {title: 'Occitan (post 1500)', value: 'oc'},
  {title: 'Ojibwa', value: 'oj'},
  {title: 'Oriya', value: 'or'},
  {title: 'Oromo', value: 'om'},
  {title: 'Ossetian; Ossetic', value: 'os'},
  {title: 'Pali', value: 'pi'},
  {title: 'Panjabi; Punjabi', value: 'pa'},
  {title: 'Persian', value: 'fa'},
  {title: 'Polish', value: 'pl'},
  {title: 'Portuguese', value: 'pt'},
  {title: 'Pushto; Pashto', value: 'ps'},
  {title: 'Quechua', value: 'qu'},
  {title: 'Romanian; Moldavian; Moldovan', value: 'ro'},
  {title: 'Romansh', value: 'rm'},
  {title: 'Rundi', value: 'rn'},
  {title: 'Russian', value: 'ru'},
  {title: 'Samoan', value: 'sm'},
  {title: 'Sango', value: 'sg'},
  {title: 'Sanskrit', value: 'sa'},
  {title: 'Sardinian', value: 'sc'},
  {title: 'Serbian', value: 'sr'},
  {title: 'Shona', value: 'sn'},
  {title: 'Sichuan Yi; Nuosu', value: 'ii'},
  {title: 'Sindhi', value: 'sd'},
  {title: 'Sinhala; Sinhalese', value: 'si'},
  {title: 'Slovak', value: 'sk'},
  {title: 'Slovenian', value: 'sl'},
  {title: 'Somali', value: 'so'},
  {title: 'Sotho, Southern', value: 'st'},
  {title: 'South Ndebele', value: 'nr'},
  {title: 'Spanish; Castilian', value: 'es'},
  {title: 'Sundanese', value: 'su'},
  {title: 'Swahili', value: 'sw'},
  {title: 'Swati', value: 'ss'},
  {title: 'Swedish', value: 'sv'},
  {title: 'Tagalog', value: 'tl'},
  {title: 'Tahitian', value: 'ty'},
  {title: 'Tajik', value: 'tg'},
  {title: 'Tamil', value: 'ta'},
  {title: 'Tatar', value: 'tt'},
  {title: 'Telugu', value: 'te'},
  {title: 'Thai', value: 'th'},
  {title: 'Tibetan', value: 'bo'},
  {title: 'Tigrinya', value: 'ti'},
  {title: 'Tonga (Tonga Islands)', value: 'to'},
  {title: 'Tsonga', value: 'ts'},
  {title: 'Tswana', value: 'tn'},
  {title: 'Turkish', value: 'tr'},
  {title: 'Turkmen', value: 'tk'},
  {title: 'Twi', value: 'tw'},
  {title: 'Uighur; Uyghur', value: 'ug'},
  {title: 'Ukrainian', value: 'uk'},
  {title: 'Urdu', value: 'ur'},
  {title: 'Uzbek', value: 'uz'},
  {title: 'Venda', value: 've'},
  {title: 'Vietnamese', value: 'vi'},
  {title: 'Volapük', value: 'vo'},
  {title: 'Walloon', value: 'wa'},
  {title: 'Welsh', value: 'cy'},
  {title: 'Western Frisian', value: 'fy'},
  {title: 'Wolof', value: 'wo'},
  {title: 'Xhosa', value: 'xh'},
  {title: 'Yiddish', value: 'yi'},
  {title: 'Yoruba', value: 'yo'},
  {title: 'Zhuang; Chuang', value: 'za'},
  {title: 'Zulu', value: 'zu'},
]
